# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  
  config.vm.box_check_update = true
  
  config.vm.synced_folder "./vagrant_data", "/vagrant_data"
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update && sudo apt-get -y upgrade

    sudo apt-get -y install git wget vim tmux build-essential curl unzip fish

    sudo wget -q -O- https://github.com/hugsy/gef/raw/master/scripts/gef.sh | sh
    sudo python3 -m pip install capstone unicorn keystone-engine ropper

    sudo apt-get -y install qemu-system

    cd /vagrant_data

    ./armv6_stretch/get.sh

  SHELL
end
