# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/xenial64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "./vagrant_data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update && sudo apt-get -y upgrade

    sudo apt-get -y install git wget vim tmux build-essential curl unzip

    sudo wget -q -O- https://github.com/hugsy/gef/raw/master/scripts/gef.sh | sh

    sudo apt-get -y install qemu-system

    cd /vagrant_data

    # Download qemu Raspberry Pi kernel images:
    git clone https://github.com/dhruvvyas90/qemu-rpi-kernel.git

    # Download the latests Raspbian from:
    # - http://downloads.raspberrypi.org/raspbian/images
    # Into /vagrant_data
    wget http://downloads.raspberrypi.org/raspbian/images/raspbian-2019-04-09/2019-04-08-raspbian-stretch.zip
    unzip 2019-04-08-raspbian-stretch.zip
    qemu-img convert -f raw -O qcow2 2019-04-08-raspbian-stretch.img raspbian-stretch-lite.qcow
    qemu-img resize raspbian-stretch-lite.qcow +2G

    qemu-system-arm \
      -M versatilepb \
      -cpu arm1176 \
      -m 256 \
      -hda ./raspbian-stretch-lite.qcow \
      -net nic \
      -net user,hostfwd=tcp::5022-:22 \
      -dtb ./qemu-rpi-kernel/versatile-pb.dtb \
      -kernel ./qemu-rpi-kernel/kernel-qemu-4.14.79-stretch \
      -append "root=/dev/sda2 rootfstype=ext4 rw"\
      -no-reboot \
      -nographic

  SHELL
end
