#!/usr/bin/env fish

sysctl -w kernel.randomize_va_space=0

echo ". . . . . rm all .bin from /src"
rm (ls /src/protostar-challenges | grep .bin)
echo ". . . . . generating new binaries from source"
for file in (ls /src/protostar-challenges)
    echo compilling $file...
    gcc \
        -w \
        -g -m32 \
        -fno-stack-protector   \
        -fno-asynchronous-unwind-tables   \
        -mpreferred-stack-boundary=2   \
        -z execstack  \
        /src/protostar-challenges/$file \
        -o (echo /src/protostar-challenges/$file | cut -d"." -f1).bin ; and echo compiled
end