#!/usr/bin/env bash

objdump -d $1
echo "==================================="

shellcode=$(objdump -d $1 | grep '[0-9a-f]:' | grep -v 'file' | cut -f2 -d: | cut -f1-6 -d' ' | tr -s ' ' | tr '\t' ' ' | sed 's/ $//g' | sed 's/ / /g' | paste -d '' -s | sed 's/^/"/' | sed 's/$/"/g' | sed 's/\"//g')
echo "shellcode:"
echo $shellcode
echo "-- -- -- -- --"
echo "shellcode lenght:"
echo $shellcode | sed 's/ //g' | wc -c
echo "-- -- -- -- --"
echo $shellcode | sed 's/ /\\x/g' | paste -d '' -s | sed 's/^/"/' | sed 's/$/"/g' | sed 's/\"//g'
echo "-- -- -- -- --"
